# Terraform Action to promote content and redirects from staging to production
name: Promote Docs Staging to Production
on:
  workflow_dispatch:

jobs:
  content:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/redirect_creation
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_KEY }}
          aws-region: us-east-1

      - name: Promote Staging Content to Production
        run:
          aws s3 sync s3://stage-docsstageliquibasecom-origin/ s3://prod-docsliquibasecom-origin/ --delete --exclude "robots.txt"
          
  redirects:
    runs-on: ubuntu-20.04
    env:
      TF_VAR_env: "prod"
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
    defaults:
      run:
        working-directory: scripts/redirect_creation
    steps:
      - uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DOCS_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_AWS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=$TF_VAR_env.remote.tfbackend 

      - name: Terraform Apply
        run: terraform apply -auto-approve